export const PERMISSION_GROUP = {
  // ===== QUẢN LÝ BÀI VIẾT =====
  QUAN_LY_BAI_VIET: "tt_BaiViet",
  QUY_TRINH_BAI_VIET: "tt_QuyTrinh",
  CHUYEN_TRANG_DIA_PHUONG: "tt_InvestmentMap",

   // ===== NGHIEP VU - KCN KKT =====
  QUAN_LY_KHU_CONG_NGHIEP: "nv_KhuCongNghiep",
  QUAN_LY_KHU_CONG_NGHIEP_SINH_THAI: "nv_KhuCongNghiepSinhThai",
  QUAN_LY_KHU_CHE_XUAT: "nv_KhuCheXuat",
  QUAN_LY_KHU_PHI_THUE_QUAN: "nv_KhuPhiThueQuan",
  QUAN_LY_KHU_THUONG_MAI_TU_DO: "nv_KhuThuongMaiTuDo",
  QUAN_LY_MO_HINH_KHU_KHAC: "nv_MHKhuKhac",
  QUAN_LY_MO_HINH_KHU_KHAC_CHO_PHE_DUYET: "nv_MHKhuKhac_ld_chopheduyet",
  QUAN_LY_BAN_VE_MAT_BANG: "nv_QLBanVeMatBang",
  QUAN_LY_QUY_DAT: "nv_QLQuyDat",
  QUAN_LY_THONG_TIN_CHO_THUE_DAT: "nv_ThongTinChoThueDat",
  QUAN_LY_DU_AN_DAU_TU: "nv_DuAnDauTu_KCN_KKT",
  GIOI_THIEU_MOI_TRUONG_DAU_TU: "nv_GioiThieuMoiTruongDauTu",
  TRA_CUU_GIOI_THIEU_MOI_TRUONG_DAU_TU: "nv_TraCuuGioiThieuMoiTruongDauTu",
  QUAN_LY_THEO_DOI_HO_SO: "nv_TheoDoiHoSo",
  TRA_CUU_TH_KCN_KKT: "nv_TraCuuTongHop",
  QUAN_LY_TINH_TRANG_DAT_CHO_THUE: "nv_TinhTrangDatChoThue",
  QUAN_LY_THU_PHI_THUE_QUY_DAT: "nv_ThuPhiThueQuyDat",
  QUAN_LY_LICH_DU_KIEN_THU_PHI_THUE_QUY_DAT: "nv_LichDuKienThuPhiThueQuyDat",
  QUAN_LY_THANH_TOAN_THUE_DAT: "nv_ThanhToanThueDat",
  QUAN_LY_THONG_TIN_KIEM_TRA: "nv_ThongTinKiemTraKcnKkt",
  CHUYEN_DOI_LOAI_HINH: "nv_ChuyenDoiLoaiHinh",

  // ===== KKT =====
  QUAN_LY_KHU_KINH_TE: "nv_KhuKinhTe",
  KHU_KINH_TE_LANH_DAO: "nv_KhuKinhTe_LD",
  KHU_KINH_TE_BAN_QUAN_LY: "nv_KhuKinhTe_BQL",
  KHU_KINH_TE_CHU_DAU_TU: "nv_KhuKinhTe_CDT",


  // ===== BAOCAO - KCN KKT =====
  DASHBOARD_KCN_KKT: "Dasboard_KCNKKT",
  BAO_CAO_QUY_DAT: "BaoCaoQuyDat",
  BAO_CAO_NHA_DAU_TU: "BaoCaoNhaDauTu",
  BAO_CAO_NHA_DAU_TU_MOI: "BaoCaoNhaDauTuMoi",
  BAO_CAO_HA_TANG: "BaoCaoHaTang",
  BAO_CAO_TINH_HINH_SAN_XUAT: "BaoCaoTinhHinhSanXuat",
  BAO_CAO_PHAN_BO_LAO_DONG: "BaoCaoPhanBoLaoDong",
  BAO_CAO_BAO_VE_MOI_TRUONG: "BaoCaoBaoVeMoiTruong",
  BAO_CAO_SO_SANH_DIA_PHUONG: "BaoCaoSoSanhDiaPhuong",
  BAO_CAO_CHAM_TIEN_DO_DU_AN: "BaoCaoChamTienDoDuAn",
  BAO_CAO_XEP_HANG_KCNST: "BaoCaoXepHangKCNST",
  BAO_CAO_CONG_SINH_KCNST: "BaoCaoCongSinhKCNST",
  BAO_CAO_HOAT_DONG_TMTD: "BaoCaoHoatDongTMTD",
  BAO_CAO_HOAT_DONG_PTQ: "BaoCaoHoatDongPTQ",
  BAO_CAO_HOAT_DONG_KHAC: "BaoCaoHoatDongKHAC",
  BAO_CAO_THUE_DAT: "BaoCaoThueDat",
  BAO_CAO_SO_SANH_TANG_TRUONG_VON_DAU_TU_THEO_KY: "nv_BaoCao_SoSanhTangTruongVonDauTuTheoKy",
  BAO_CAO_SO_SANH_KCN_KKT_GIUA_CAC_NAM: "nv_BaoCao_SoSanhKCNKKTGiuaCacNam",
  BAO_CAO_TUY_BIEN: "bctt_BaoCaoTuyBien",
  THONG_KE_XEP_HANG_KCN_CO_TI_LE_LAP_DAY_CAO: "nv_BaoCao_ThongKeXepHangKCNCoTiLeLapDayCao",
  CANH_CAO_CAC_KCN_CO_TI_LE_LAP_DAY_THAP: "nv_BaoCao_CanhCaoCacKcnCoTiLeLapDayThap",

  // ===== BAOCAO - XTDT =====
  BAO_CAO_TONG_HOP_CHUONG_TRINH_XTDT_DIA_PHUONG: "nv_BaoCao_TongHopChuongTrinhXtdtDiaPhuong",
  BAO_CAO_TONG_HOP_HOAT_DONG_DOI_NGOAI_CAP_CAO_NHA_NUOC: "nv_BaoCao_TongHopHoatDongDoiNgoaiCapCaoNhaNuoc",
  BAO_CAO_TONG_HOP_HOAT_DONG_XTDT_KHONG_SU_DUNG_NSNN: "nv_BaoCao_TongHopHoatDongXtdtKhongSuDungNsnn",

  // ===== NGHIEP VU - CDT =====
  QUAN_LY_KHU_CONG_NGHIEP_CDT: "nv_KhuCongNghiep_KhuKinhTe_CDT",
  QUAN_LY_KHU_CONG_NGHIEP_SINH_THAI_CDT: "nv_KhuCongNghiepSinhThai_CDT",
  QUAN_LY_KHU_KINH_TE_CDT: "nv_KhuKinhTe_CDT",
  QUAN_LY_KHU_PHI_THUE_QUAN_CDT: "nv_KhuPhiThueQuan_CDT",
  QUAN_LY_KHU_THUONG_MAI_TU_DO_CDT: "nv_KhuThuongMaiTuDo_CDT",
  QUAN_LY_MO_HINH_KHU_KHAC_CDT: "nv_MHKhuKhac_CDT",
  QUAN_LY_DU_AN_DAU_TU_CDT: "nv_DuAnDauTu_CDTs",

  // ===== DANH MUC - DM chinh =====
  DM_BO_NGANH: "dm_BoNganh",
  DM_CAN_CU_PHAP_LY: "dm_CanCuPhapLy",
  DM_CHI_NHANH: "dm_ChiNhanh",
  DM_CHUC_VU: "dm_ChucVu",
  DM_CHU_DAU_TU: "dm_ChuDauTu",
  DM_CHUYEN_VIEN_KKT: "dm_ChuyenVienKKT",
  DM_CHUYEN_VIEN_SO_KHDT: "dm_ChuyenVienSoKHDT",
  DM_CONG_TRINH_XAY_DUNG: "dm_CongTrinhXayDung",
  DM_CO_QUAN: "dm_CoQuan",
  DM_DAI_DIEN_XTDT: "dm_DaiDienXTDT",
  DM_DAN_TOC: "dm_DanToc",
  DM_DICH_VU_CONG: "DichVuCong",
  DM_DICH_VU_XNK: "dm_DichVuXNK",
  DM_DOANH_NGHIEP: "dm_DoanhNghiep",
  DM_DOI_TAC_DAU_TU: "dm_DoiTacDauTu",
  DM_DON_VI_SOAN_THAO: "dm_DonViSoanThao",
  DM_DON_VI_TINH: "dm_DonViTinh",
  DM_EBOPS: "dm_EBOPS",
  DM_GIOI_TINH: "dm_GioiTinh",
  DM_HANG_HOA_XNK: "dm_HangHoaXNK",
  DM_HE_THONG_NSP: "dm_HeThongNSP",
  DM_HINH_THUC_DAU_TU: "dm_HinhThucDauTu",
  DM_HINH_THUC_DAU_TU_XTDT: "dm_HinhThucDauTuXTDT",
  DM_HINH_THUC_GOP_VON: "dm_HinhThucGopVon",
  DM_ISIC: "dm_ISIC",
  DM_KCN_QUY_HOACH: "dm_KCNQuyHoach",
  DM_KKT_QUY_HOACH: "dm_KKTQuyHoach",
  DM_KHU_KINH_TE: "dm_KhuKinhTe",
  DM_KHU_VUC_DIA_LY: "dm_KhuVucDiaLy",
  DM_LINH_VUC_CAM_DAU_TU: "dm_LinhVucCamDauTu",
  DM_LINH_VUC_DU_AN: "dm_LinhVucDuAn",
  DM_LINH_VUC_UU_DAI: "dm_LinhVucUuDai",
  DM_LINH_VUC_VAN_BAN: "dm_LinhVucVanBan",
  DM_LOAI_CHUONG_TRINH_XTDT: "dm_LoaiChuongTrinhXTDT",
  DM_LOAI_DOANH_NGHIEP: "dm_LoaiDoanhNghiep",
  DM_LOAI_HINH_GIAO_DUC: "dm_LoaiHinhGiaoDuc",
  DM_LOAI_HOAT_DONG_XTDT: "dm_LoaiHoatDongXTDT",
  DM_LOAI_HO_SO: "dm_LoaiHoSo",
  DM_LOAI_KHU_CHUC_NANG: "dm_LoaiKhuChucNang",
  DM_LOAI_SU_KIEN_XTDT: "dm_LoaiSuKienXTDT",
  DM_LOAI_TY_GIA_NGOAI_TE: "dm_LoaiTyGiaNgoaiTe",
  DM_LOAI_VAN_BAN: "dm_LoaiVanBan",
  DM_LOAI_VAN_BAN_PHAP_QUY: "dm_LoaiVanBanPhapQuy",
  DM_LOAI_VON_DAU_TU: "dm_LoaiVonDauTu",
  DM_NGANH_KINH_TE: "dm_NganhKinhTe",
  DM_NGANH_NGHE_DAC_BIET_UU_DAI: "dm_NganhNgheDacBietUuDai",
  DM_NGAY_NGHI: "dm_NgayNghi",
  DM_NGHE_NGHIEP: "dm_NgheNghiep",
  DM_NGOAI_TE: "dm_NgoaiTe",
  DM_NHA_DAU_TU: "dm_NhaDauTu",
  DM_PHONG_BAN_KKT: "dm_PhongBan_KKT",
  DM_PHONG_BAN_SO_KHDT: "dm_PhongBanSoKHDT",
  DM_PHUONG_THUC_DAU_TU: "dm_PhuongThucDauTu",
  DM_QUOC_GIA: "dm_QuocGia",
  DM_QUOC_TICH: "dm_QuocTich",
  DM_SAN_PHAM_CONG_NGHIEP: "dm_SanPhamCongNghiep",
  DM_SITC: "dm_SITC",
  DM_SO_KHDT: "dm_SoKHDT",
  DM_THANH_PHAN_KINH_TE: "dm_ThanhPhanKinhTe",
  DM_THU_TUC_HANH_CHINH: "ThuTucHanhChinh",
  DM_TI_GIA_NGOAI_TE_TRUNG_BINH_KY: "dm_TiGiaNgoaiTeTrungBinh_Ky",
  DM_TINH_THANH_PHO: "dm_TinhThanhPho",
  DM_TINH_THANH_PHO_QUOC_GIA: "dm_TinhThanhPhoQuocGia",
  DM_TINH_TRANG_DU_AN_DAU_TU_VAO_KHU: "dm_TinhTrangDuAnDauTuVaoKhu",
  DM_TINH_TRANG_HOAT_DONG_KCN: "dm_TinhTrangHoatDong_KCN",
  DM_TO_CHUC_QUOC_TE: "dm_ToChucQuocTe",
  DM_TON_GIAO: "dm_TonGiao",
  DM_TRINH_DO_HOC_VAN: "dm_TrinhDoHocVan",
  DM_UY_BAN_NHAN_DAN: "dm_UyBanNhanDan",
  DM_VUNG_KINH_TE: "dm_VungKinhTe",
  DM_XA_PHUONG_THI_TRAN: "dm_XaPhuongThiTran",
  DM_DOI_TUONG_THAM_GIA: "dm_DoiTuongThamGia",
  DM_QUY_HOACH_KCN_KKT: "dm_QuyHoach_KCN_KKT",

  // ===== QUAN TRI HE THONG =====
  QT_DON_VI: "ht_DonVi",
  QT_NGUOI_DUNG: "ht_TaiKhoan",
  QT_VAI_TRO: "ht_VaiTro",
  QT_NHOM_QUYEN: "ht_NhomQuyen",
  QT_MENU: "ht_Menu",

  // ===== XTDT =====
  DANH_MUC_LOAI_CHUONG_TRINH_XTDT: "dm_LoaiChuongTrinhXTDT",
  DANH_MUC_DU_AN_X_T_D_T: "nv_DanhMucDuAnXTDT",
  DANH_MUC_DU_AN_X_T_D_T__DIA_PHUONG: "nv_DanhMucDuAnXTDT_DiaPhuong",
  DU_AN_KEU_GOI_DAU_TU: "nv_DuAnKeuGoiDauTu",
  TRA_CUU_DU_AN_KEU_GOI_DAU_TU: "nv_TraCuDuAnKeuGoiDauTu",
  DU_AN_THU_HUT_DAU_TU_DIA_PHUONG: "nv_DuAnThuHutDauTuDiaPhuong",
  TRA_CUU_DU_AN_THU_HUT_DAU_TU_DIA_PHUONG: "nv_TraCuuDuAnThuHutDauTuDiaPhuong",
  CAU_HINH_CANH_BAO_MOC_THOI_GIAN: "nv_CauHinhCanhBaoMocThoiGian",

  // ===== XTDT - Chuong trinh =====
  BANG_TONG_HOP_BO_NGANH: "nv_BangTongHopBoNganh",
  BANG_TONG_HOP_DIA_PHUONG: "nv_BangTongHopDiaPhuong",
  BANG_TONG_HOP_QUOC_GIA: "nv_BangTongHopQuocGia",
  QUYET_DINH_THUC_HIEN_BO_NGANH: "nv_QuyetDinhThucHienBoNganh",
  QUYET_DINH_THUC_HIEN_DIA_PHUONG: "nv_QuyetDinhThucHienDiaPhuong",
  QUYET_DINH_THUC_HIEN_QUOC_GIA: "nv_QuyetDinhThucHienQuocGia",
  VAN_BAN_DU_KIEN_BO_NGANH: "nv_VanBanDuKienBoNganh",
  VAN_BAN_DU_KIEN_BO_NGANH__GOP_Y: "nv_VanBanDuKienBoNganh_GopY",
  VAN_BAN_DU_KIEN_BO_NGANH__PHE_DUYET: "nv_VanBanDuKienBoNganh_PheDuyet",
  VAN_BAN_DU_KIEN_DIA_PHUONG: "nv_VanBanDuKienDiaPhuong",
  VAN_BAN_DU_KIEN_DIA_PHUONG__GOP_Y: "nv_VanBanDuKienDiaPhuong_GopY",
  VAN_BAN_DU_KIEN_DIA_PHUONG__PHE_DUYET: "nv_VanBanDuKienDiaPhuong_PheDuyet",
  DE_AN_HOAT_DONG: "nv_DeAnHoatDong",
  DE_XUAT_QUOC_GIA: "nv_DeXuatQuocGia",
  DE_XUAT_QUOC_GIA__GOP_Y: "nv_DeXuatQuocGia_GopY",
  DE_XUAT_QUOC_GIA__PHE_DUYET: "nv_DeXuatQuocGia_PheDuyet",
  DE_XUAT_QUOC_GIA__TRA_CUU: "nv_DeXuatQuocGia_TraCuu",
  VAN_BAN_DON_DOC: "nv_VanBanDonDoc",
  HOP_DONG_GIAO_NHIEM_VU_QUOC_GIA: "nv_HopDongGiaoNhiemVuQuocGia",
  VAN_BAN_CHI_DAO: "nv_VanBanChiDao",

  // ===== XTDT - Dieu chinh =====
  DE_NGHI_DIEU_CHINH: "nv_DeNghiDieuChinh",
  DE_NGHI_DIEU_CHINH_BO_NGANH: "nv_DeNghiDieuChinhBoNganh",
  DE_NGHI_DIEU_CHINH_DIA_PHUONG: "nv_DeNghiDieuChinhDiaPhuong",
  DIEU_CHINH_QUYET_DINH_THUC_HIEN_BO_NGANH: "nv_DieuChinhQuyetDinhThucHienBoNganh",
  DIEU_CHINH_QUYET_DINH_THUC_HIEN_DIA_PHUONG: "nv_DieuChinhQuyetDinhThucHienDiaPhuong",
  DIEU_CHINH_QUYET_DINH_THUC_HIEN_QUOC_GIA: "nv_DieuChinhQuyetDinhThucHienQuocGia",
  DIEU_CHINH_DU_KIEN_BO_NGANH__GOP_Y: "nv_DieuChinhDuKienBoNganh_GopY",
  DIEU_CHINH_DU_KIEN_BO_NGANH__PHE_DUYET: "nv_DieuChinhDuKienBoNganh_PheDuyet",
  DIEU_CHINH_DU_KIEN_DIA_PHUONG__GOP_Y: "nv_DieuChinhDuKienDiaPhuong_GopY",
  DIEU_CHINH_DU_KIEN_DIA_PHUONG__PHE_DUYET: "nv_DieuChinhDuKienDiaPhuong_PheDuyet",
  DIEU_CHINH_DE_XUAT_QUOC_GIA__GOP_Y: "nv_DieuChinhDeXuatQuocGia_GopY",
  DIEU_CHINH_DE_XUAT_QUOC_GIA__PHE_DUYET: "nv_DieuChinhDeXuatQuocGia_PheDuyet",

  // ===== XTDT - Hoat dong khac =====
  PHUONG_AN_XTDT_DOI_NGOAI_CAP_CAO: "nv_PhuongAnXtdtDoiNgoaiCapCao",
  PHUONG_AN_XTDT__GOP_Y: "nv_PhuongAnXtdt_GopY",
  HOAT_DONG_XT_HON_HOP: "nv_HoatDongXtHonHop",
  HOAT_DONG_XT_HON_HOP__GOP_Y: "nv_HoatDongXtHonHop_GopY",
  HOAT_DONG_XTDT_KHONG_SU_DUNG_NSNN: "nv_HoatDongXtdtKhongSuDungNsnn",

  // ===== XTDT - MOU =====
  BO_NGANH_M_O_U: "nv_BoNganhMOU",
  BO_NGANH_M_O_U_GUI: "nv_MOUBoNganh_Gui",
  BO_NGANH_M_O_U_BAO_CAO: "nv_BoNganhMOUBaoCaoThucHien",

  DIA_PHUONG_M_O_U: "nv_DiaPhuongMOU",
  DIA_PHUONG_M_O_U_GUI: "nv_MOUDiaPhuong_Gui",
  DIA_PHUONG_M_O_U_BAO_CAO: "nv_DiaPhuongMOUBaoCaoThucHien",

  DOANH_NGHIEP_M_O_U: "nv_DoanhNghiepMOU",
  DOANH_NGHIEP_M_O_U_GUI: "nv_MOUDoanhNghiep_Gui",
  DOANH_NGHIEP_M_O_U_BAO_CAO: "nv_DoanhNghiepMOUBaoCaoThucHien",



  // ===== XTDT - Danh muc =====
  LOAI_DU_AN: "dm_LoaiDuAn",
};


export const PERMISSIONS_DETAIL = {
  THEM: "Them",
  SUA: "Sua",
  XOA: "Xoa",
  XEM: "Xem",
  TIM_KIEM: "TimKiem",
  BIEN_TAP_BAI_VIET: "BienTapBaiViet",
  DUYET_XUAT_BAN_BAI_VIET: "DuyetXuatBanBaiViet",
  PHE_DUYET: "PheDuyet",
  CONG_BO: "CongBo",
  HUY_CONG_BO: "HuyCongBo",
  IMPORT: "Import",
  EXPORT: "Export",
  GUI_DUYET: "GuiDuyet",
  TrinhLDDuyet: "TrinhLDDuyet",
  TrinhLDPhong: "TrinhLDPhong",
  TrinhLDCuc: "TrinhLDCuc",
  TrinhLDBo: "TrinhLDBo",
  GIAO_TRIEN_KHAI: "GiaoTrienKhai",
  TIEP_NHAN: "TiepNhan",
  XacNhanKy: "XacNhanKy",
  GUI_XIN_YC_BTC: "GuiXinYcbTC",
  GopY: "GopY",
  CHON_CHUONG_TRINH: "ChonLoaiChuongTrinh",
  LichSuChinhSua: "LichSuChinhSua",
  TuChoi: "TuChoi",
  LanhDaoBoXacNhan: "LanhDaoBoXacNhan",
  LanhDaoBoCauHinhKy: "LanhDaoBoCauHinhKy",
  LanhDaoPhongXacNhan: "LanhDaoPhongXacNhan",
  LanhDaoPhongCauHinhKy: "LanhDaoPhongCauHinhKy",
  LanhDaoCucXacNhan: "LanhDaoCucXacNhan",
  LanhDaoCucCauHinhKy: "LanhDaoCucCauHinhKy",
  XEM_LICH_SU: "XemLichSu",
};

export const ROLES = {
  QUAN_TRI_VIEN: "ADMIN",
  LANH_DAO: "BQL_KCN_001",
  CDT_KCN: "CDT_KCN",
  CDT_KKT: "CDT_KKT",
  BQL_KCN_001: "CB_BQL_KCN_001",
  CB_UBND_TINH: "CB_UBND_TINH",
  CBCM_BO: "CMCMCBN",
  LD_BO: "LD_Bo",
  LD_BO_TAI_CHINH: "LD_Bo_Tai_Chinh",
  LDUBNDT: "LDUBNDT",
  CBUBNDT: "CBUBNDT",
  LD_CUC: "LanhDaoCucDTNN",
  CB_CUC: "canbochuyenmoncuc",
};

